import React from "react";
import Head from "next/head";
import CalendarComponent from "../components/Calendar";
import { UpcomingEvent } from "../components/Calendar/upcoming-event";
import { NavigationBar } from "@/components/Navigation";
import styles from "@/styles/Calendar.module.css";

const CalendarPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Eco Findr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.content}>
          <h1 className={styles.heading}>Calendar</h1>
          <CalendarComponent />
          <div className={styles.upcoming}>
            <h3 className={styles.h3}>Upcoming Events</h3>
            <UpcomingEvent />
          </div>
        </div>
        <NavigationBar />
      </main>
    </div>
  );
};

export default CalendarPage;