import Head from "next/head";
import CalendarComponent from "../components/CreateEvents";
import { UpcomingEvent } from "../components/CreateEvents/upcoming-events";
import { NavigationBar } from "@/components/Navigation";
import styles from "@/styles/Calendar.module.css";
import React, { useState } from "react";
import HamburgerMenu from "@/components/HamburgerMenu";

const CalendarPage = () => {
  const [showHamburgerMenu, setShowHamburgerMenu] = useState(false);

  const toggleHamburgerMenu = () => {
    setShowHamburgerMenu(!showHamburgerMenu);
  };

  return (
    <>
      <Head>
        <title>Eco Findr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
      <div className={styles.container}>
      <div className={styles.contentWrapper}>

          <img
            src={"/images/hamburgerMenu.png"}
            className={styles.menuIcon}
            width="40px"
            height="auto"
            alt="hamburger menu"
            onClick={toggleHamburgerMenu}
          />
          {showHamburgerMenu && <HamburgerMenu closeMenu={toggleHamburgerMenu} />}
          <div className={styles.content}>
            <h1 className={styles.heading}>Calendar</h1>
            <CalendarComponent />
            <div className={styles.upcoming}>
              <h3 className={styles.h3}>Upcoming Events</h3>
              <UpcomingEvent />
            </div>
          </div>
          </div>
          <NavigationBar />
          </div>
        </main>
    </>
  );
};

export default CalendarPage;