import Head from "next/head";
import styles from "@/styles/EventHistory.module.css";
import Cards from "@/components/Cards/cards-events";
import React, { useState } from "react";
import HamburgerMenu from "@/components/HamburgerMenu";
import Link from "next/link";
import { NavigationBar } from "@/components/Navigation";

export default function EventHistory() {
  const [showHamburgerMenu, setShowHamburgerMenu] = useState(false);

  const toggleHamburgerMenu = () => {
    setShowHamburgerMenu(!showHamburgerMenu);
  };

  return (
    <>
      <Head>
        <title>Eco Findr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} `}>
        <div className={styles.container}>
        <div className={styles.contentWrapper}>
        <Link href="/Profile"><img
            src={"/images/back-button.png"}
            className={styles.backIcon}
            width="20px"
            height="auto"
            alt="back button"
          /></Link>
          <img
            src={"/images/hamburgerMenu.png"}
            className={styles.menuIcon}
            width="40px"
            height="auto"
            alt="hamburger menu"
            onClick={toggleHamburgerMenu}
          />
          {showHamburgerMenu && <HamburgerMenu closeMenu={toggleHamburgerMenu} />}
          <div className={styles.chartsWrapper}>
                            <h2>Events History</h2>
                            </div>

          <div className={styles.cards}>

          <Cards
              title="Tree Planting"
              location="987 Cedar Road, Vancouver, BC"
              date="December 5th"
              time="9:00 AM"
              imgSrc="/images/tree-planting.jpeg"
              alt="tree-planting"
            />
            <Cards
              title="Biking Tour"
              location="123 Bike Lane, Vancouver, BC"
              date="September 25th"
              time="9:00 AM"
              imgSrc="/images/biking-tour.jpeg"
              alt="gardening"
            />
            <Cards title="Biking" 
                  location="456 Elm Street, Downtown Vancouver, BC"
                  date="August 15th"
                  time="2:30 PM"
            imgSrc="/images/biking.jpeg" 
            alt="biking"
            
             />
          </div>
          </div>
          <NavigationBar />
        </div>
      </main>
    </>
  );
}
