import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Cards from "@/components/Cards"
import Chips from "@/components/Chips";

export default function Home() {
  return (
    <>
      <Head>
        <title>Eco Findr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} `}>
      <Cards title="Biking" imgSrc="/images/biking.jpeg" alt="biking" />
      <Chips/>
      </main>
    </>
  );
}
