import Head from "next/head";
import React, { useState } from 'react';
import { NavigationBar } from "@/components/Navigation";
import styles from "@/styles/LearnMore.module.css";
import HamburgerMenu from "@/components/HamburgerMenu";
import DoughnutChart from "@/components/DonutChart";
import Pie from "@/components/PieChart";

const LearnMore = () => {
    const [showHamburgerMenu, setShowHamburgerMenu] = useState(false);

    const toggleHamburgerMenu = () => {
        setShowHamburgerMenu(!showHamburgerMenu);
    };

    return (
        <>
            <Head>
                <title>Eco Findr</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} `}>

            <div className={styles.container}>
                    <div className={styles.contentWrapper}>
                        <img src={"/images/hamburgerMenu.png"}
                            className={styles.menuIcon}
                            width="40px"
                            height="auto"
                            alt="hamburger menu"
                            onClick={toggleHamburgerMenu} />
                        {showHamburgerMenu && <HamburgerMenu closeMenu={toggleHamburgerMenu} />}
                        <div className={styles.chartsWrapper}>
                            <h2>Learn More</h2>
                            <p>Gain insights at a glance!</p>
                            <div className={styles.doughnutChart} >
                                <DoughnutChart />
                            </div>
                            <div className={styles.pieChart} >
                                <Pie />
                            </div>
                        </div>
                    </div>

                    <NavigationBar />
            </div>
            </main>

        </>
    );
};

export default LearnMore;
