import Head from "next/head";
import LargeButton from '@/components/LargeButton';
import React from 'react';
import { NavigationBar } from "@/components/Navigation";
import styles from "@/styles/Profile.module.css";

const Profile = () => {
  
  return (
    <>
      <Head>
    <title>Eco Findr</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    
  <img className={styles.profileImg} src="/images/blank-profile.webp" width={100} height={100}/>
<div>
      <LargeButton className={styles.lgBtn} text="Saved Events"/>
      </div>
      <div>
      <LargeButton text="Event History"/>
      </div>
    <NavigationBar/>
   
    </>

    
  );
};

export default Profile;